environment:
  matrix:
    - node_version: "4.6"
    - node_version: "5.12"
    - node_version: "6.7"
install:
  - ps: Install-Product node $env:node_version
  - npm install
  - npm install mocha -g

platform:
  - x86
  - x64

build: off

test_script:
  - npm test
